export const MESSAGE = {
    verifyEmailErr: 'Please verify your email address',
    sentEmailResetPassword: 'password reset email sent',
    loginError: 'The username or password is incorrect.Please input again',
    notFoundEmail: 'Could not find your Account, please try again',
    signUpSuccess: 'Thanks! A verifycation link has been sent to your email account, please check',
    createClientSuccess: 'Greate! Create client successfully',
    createBrandSuccess: 'Greate! Create brand successfully',
    createCampaignSuccess: 'Greate! Create campaign successfully',
    createAppSuccess: 'Greate! Create app successfully',
    updateAppSuccess: 'Greate! Update app successfully',
    updateUserSuccess: 'Update infomation successfully',
    sendSuccess: 'Successfully',
    paymentSuccess: 'Thanks! purchase success',
};
